//! HTTP integration + schema-parity tests for the `/graphql` endpoint (plan
//! T6.1/T6.2, §3.12). Boots the axum app on a real ephemeral socket (same
//! harness as `registry_http.rs`) with a registry-enabled `AppState`, then
//! drives every implemented GraphQL operation over both GET and POST, plus the
//! no-batching / query-safety guard and the graphene-faithful error shapes.
//!
//! Coverage:
//! * each Query operation (`mlflowGetExperiment`, `mlflowGetRun`,
//!   `mlflowGetMetricHistoryBulkInterval`, `mlflowListArtifacts`,
//!   `mlflowSearchModelVersions`) and each Mutation (`mlflowSearchRuns`,
//!   `mlflowSearchDatasets`, plus the `test`/`testMutation` echo fields);
//! * GET and POST both parse the JSON body (no query-string parsing);
//! * `LongString` scalars serialize as *quoted* integers; `Float` metric
//!   values keep Python float repr; `apiError` is always `null`;
//! * the in-band error shape (`{"data": ..., "errors": ["<message>"]}` — bare
//!   strings, failed root field `null`);
//! * the no-batching guard (root-fields / aliases / depth / total-selections)
//!   and the batched-array / missing-query rejections;
//! * content-type validation on POST (MlflowException JSON, not in-band);
//! * T6.2: the embedded SDL is byte-identical to the on-disk
//!   `autogenerated_schema.gql`, and every implemented root field is present in
//!   that schema.

use http_body_util::{BodyExt, Full};
use hyper::body::Bytes;
use hyper::{Method, Request, StatusCode};
use hyper_util::client::legacy::Client;
use hyper_util::rt::TokioExecutor;
use metrics_exporter_prometheus::PrometheusBuilder;
use mlflow_registry::RegistryStore;
use mlflow_server::{build_app_with_recorder, AppState, ServerConfig};
use mlflow_store::{Db, PoolConfig, TrackingStore};
use serde_json::{json, Value};
use std::path::{Path, PathBuf};
use tokio::net::TcpListener;

const WS: &str = "default";

// The fixture's pre-seeded entities (see `tests/fixtures/tracking.db`).
const FIXTURE_EXP_ID: &str = "1";
const FIXTURE_RUN_ID: &str = "f6f9b188dd2845c0ae79e10bce95d692";

fn fixture_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("tracking.db")
}

struct TempDb {
    path: PathBuf,
}

impl TempDb {
    fn new(tag: &str) -> Self {
        static COUNTER: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
        let n = COUNTER.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!(
            "mlflow_rust_server_graphql_{}_{}_{}.db",
            tag,
            std::process::id(),
            n
        ));
        let _ = std::fs::remove_file(&path);
        std::fs::copy(fixture_path(), &path).expect("copy fixture");
        TempDb { path }
    }

    fn uri(&self) -> String {
        format!("sqlite:///{}", self.path.display())
    }
}

impl Drop for TempDb {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(&self.path);
    }
}

struct TestServer {
    base: String,
    shutdown: Option<tokio::sync::oneshot::Sender<()>>,
    handle: Option<tokio::task::JoinHandle<()>>,
    _db: TempDb,
    registry: RegistryStore,
}

impl TestServer {
    async fn start(tag: &str) -> Self {
        let db_file = TempDb::new(tag);

        let db = Db::connect(&db_file.uri(), PoolConfig::default())
            .await
            .expect("connect temp fixture");
        let tracking = TrackingStore::new(db.clone(), "file:///unused".to_string());
        let registry = RegistryStore::new(db);

        let config = ServerConfig {
            host: "127.0.0.1".to_string(),
            port: 0,
            static_prefix: None,
            backend_store_uri: None,
            default_artifact_root: None,
            serve_artifacts: true,
            artifacts_destination: None,
            allowed_hosts: None,
            cors_allowed_origins: None,
            x_frame_options: "SAMEORIGIN".to_string(),
        };
        let recorder = PrometheusBuilder::new().build_recorder().handle();
        let app_state =
            AppState::with_registry(tracking.clone(), registry.clone(), true, None, None);
        let app = build_app_with_recorder(&config, recorder, Some(app_state));

        let listener = TcpListener::bind(("127.0.0.1", 0)).await.expect("bind");
        let addr = listener.local_addr().expect("addr");
        let (shutdown_tx, shutdown_rx) = tokio::sync::oneshot::channel::<()>();
        let handle = tokio::spawn(async move {
            axum::serve(listener, app)
                .with_graceful_shutdown(async {
                    let _ = shutdown_rx.await;
                })
                .await
                .expect("server error");
        });

        TestServer {
            base: format!("http://{addr}"),
            shutdown: Some(shutdown_tx),
            handle: Some(handle),
            _db: db_file,
            registry,
        }
    }
}

impl Drop for TestServer {
    fn drop(&mut self) {
        if let Some(tx) = self.shutdown.take() {
            let _ = tx.send(());
        }
        if let Some(h) = self.handle.take() {
            h.abort();
        }
    }
}

struct HttpResponse {
    status: StatusCode,
    content_type: Option<String>,
    body: Vec<u8>,
}

impl HttpResponse {
    fn text(&self) -> String {
        String::from_utf8_lossy(&self.body).into_owned()
    }
    fn json(&self) -> Value {
        serde_json::from_slice(&self.body)
            .unwrap_or_else(|e| panic!("body is not JSON: {e}: {}", self.text()))
    }
}

/// Send a GraphQL request. `method` is GET or POST; both carry the JSON body
/// (graphene reads `get_json(force=True)` regardless of verb). `with_ct`
/// controls whether the `content-type: application/json` header is sent.
async fn send_raw(server: &TestServer, method: Method, body: Bytes, with_ct: bool) -> HttpResponse {
    let client = Client::builder(TokioExecutor::new()).build_http();
    let url = format!("{}/graphql", server.base);
    let build = || {
        let mut b = Request::builder().method(method.clone()).uri(&url);
        if with_ct {
            b = b.header("content-type", "application/json");
        }
        b.body(Full::<Bytes>::new(body.clone())).unwrap()
    };

    let mut last = None;
    for _ in 0..50 {
        match client.request(build()).await {
            Ok(res) => {
                let status = res.status();
                let content_type = res
                    .headers()
                    .get("content-type")
                    .and_then(|v| v.to_str().ok())
                    .map(str::to_string);
                let bytes = res.into_body().collect().await.unwrap().to_bytes();
                return HttpResponse {
                    status,
                    content_type,
                    body: bytes.to_vec(),
                };
            }
            Err(e) => {
                last = Some(e);
                tokio::time::sleep(std::time::Duration::from_millis(20)).await;
            }
        }
    }
    panic!("failed to connect: {last:?}");
}

/// POST a `{query, variables}` GraphQL request with the JSON content-type.
async fn gql(server: &TestServer, query: &str, variables: Value) -> HttpResponse {
    let body = json!({"query": query, "variables": variables});
    send_raw(
        server,
        Method::POST,
        Bytes::from(serde_json::to_vec(&body).unwrap()),
        true,
    )
    .await
}

fn assert_ok(res: &HttpResponse) {
    assert_eq!(res.status, StatusCode::OK, "{}", res.text());
    assert_eq!(
        res.content_type.as_deref(),
        Some("application/json"),
        "{}",
        res.text()
    );
    // Flask `jsonify` appends a trailing newline.
    assert!(res.body.ends_with(b"\n"), "body must end with newline");
}

// ===========================================================================
// Query.mlflowGetExperiment
// ===========================================================================

#[tokio::test]
async fn get_experiment_returns_fixture_experiment() {
    let server = TestServer::start("get_exp").await;
    let res = gql(
        &server,
        "query Q($input: MlflowGetExperimentInput!) { \
         mlflowGetExperiment(input: $input) { experiment { experimentId name lifecycleStage \
         creationTime } apiError } }",
        json!({"input": {"experimentId": FIXTURE_EXP_ID}}),
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    assert!(body["errors"].is_null(), "{}", res.text());
    let exp = &body["data"]["mlflowGetExperiment"]["experiment"];
    assert_eq!(exp["experimentId"], FIXTURE_EXP_ID);
    assert_eq!(exp["name"], "rust_store_fixture");
    assert_eq!(exp["lifecycleStage"], "active");
    // `creationTime` is a LongString → serialized as a *quoted* integer.
    assert!(exp["creationTime"].is_string(), "{}", res.text());
    // OSS never populates apiError.
    assert!(body["data"]["mlflowGetExperiment"]["apiError"].is_null());
}

#[tokio::test]
async fn get_experiment_missing_id_is_in_band_error() {
    let server = TestServer::start("get_exp_err").await;
    let res = gql(
        &server,
        "query Q { mlflowGetExperiment(input: {experimentId: \"\"}) { experiment { name } } }",
        json!({}),
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    // Failed root field is null; the store/validation error is a bare string.
    assert!(
        body["data"]["mlflowGetExperiment"].is_null(),
        "{}",
        res.text()
    );
    let errors = body["errors"].as_array().expect("errors array");
    assert_eq!(errors.len(), 1);
    assert!(
        errors[0]
            .as_str()
            .unwrap()
            .contains("Missing value for required parameter 'experiment_id'"),
        "{}",
        res.text()
    );
}

#[tokio::test]
async fn get_experiment_not_found_is_in_band_error() {
    let server = TestServer::start("get_exp_404").await;
    let res = gql(
        &server,
        "query Q { mlflowGetExperiment(input: {experimentId: \"99999\"}) { experiment { name } } }",
        json!({}),
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    assert!(
        body["data"]["mlflowGetExperiment"].is_null(),
        "{}",
        res.text()
    );
    assert_eq!(body["errors"].as_array().unwrap().len(), 1);
}

// ===========================================================================
// Query.mlflowGetRun (MlflowRunExtension: experiment + modelVersions)
// ===========================================================================

#[tokio::test]
async fn get_run_returns_info_data_and_extension_fields() {
    let server = TestServer::start("get_run").await;
    let res = gql(
        &server,
        "query Q($input: MlflowGetRunInput!) { mlflowGetRun(input: $input) { \
         run { info { runId experimentId status startTime } \
         data { metrics { key value timestamp step } params { key value } } \
         experiment { experimentId } modelVersions { name } } apiError } }",
        json!({"input": {"runId": FIXTURE_RUN_ID}}),
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    assert!(body["errors"].is_null(), "{}", res.text());
    let run = &body["data"]["mlflowGetRun"]["run"];
    assert_eq!(run["info"]["runId"], FIXTURE_RUN_ID);
    assert_eq!(run["info"]["experimentId"], FIXTURE_EXP_ID);
    assert_eq!(run["info"]["status"], "FINISHED");
    // startTime is LongString → quoted int.
    assert!(run["info"]["startTime"].is_string());
    // Metrics: `value` is a Float (bare number), timestamp/step are LongStrings.
    let metrics = run["data"]["metrics"].as_array().unwrap();
    assert!(!metrics.is_empty(), "{}", res.text());
    assert!(metrics[0]["value"].is_number());
    assert!(metrics[0]["timestamp"].is_string());
    assert!(metrics[0]["step"].is_string());
    // Extension fields resolved eagerly.
    assert_eq!(run["experiment"]["experimentId"], FIXTURE_EXP_ID);
    assert!(run["modelVersions"].is_array());
    assert!(run["modelVersions"].as_array().unwrap().is_empty());
}

#[tokio::test]
async fn get_run_accepts_run_uuid_alias() {
    let server = TestServer::start("get_run_uuid").await;
    let res = gql(
        &server,
        "query Q { mlflowGetRun(input: {runUuid: \"f6f9b188dd2845c0ae79e10bce95d692\"}) { \
         run { info { runId } } } }",
        json!({}),
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    assert!(body["errors"].is_null(), "{}", res.text());
    assert_eq!(
        body["data"]["mlflowGetRun"]["run"]["info"]["runId"],
        FIXTURE_RUN_ID
    );
}

// ===========================================================================
// Query.mlflowGetMetricHistoryBulkInterval
// ===========================================================================

#[tokio::test]
async fn metric_history_bulk_interval_returns_metrics() {
    let server = TestServer::start("metric_hist").await;
    let res = gql(
        &server,
        "query Q($input: MlflowGetMetricHistoryBulkIntervalInput!) { \
         mlflowGetMetricHistoryBulkInterval(input: $input) { \
         metrics { key value timestamp step runId } apiError } }",
        json!({"input": {"runIds": [FIXTURE_RUN_ID], "metricKey": "accuracy"}}),
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    assert!(body["errors"].is_null(), "{}", res.text());
    let metrics = body["data"]["mlflowGetMetricHistoryBulkInterval"]["metrics"]
        .as_array()
        .unwrap();
    assert_eq!(metrics.len(), 2, "{}", res.text());
    assert_eq!(metrics[0]["key"], "accuracy");
    assert_eq!(metrics[0]["runId"], FIXTURE_RUN_ID);
    assert!(metrics[0]["value"].is_number());
    assert!(metrics[0]["timestamp"].is_string());
}

#[tokio::test]
async fn metric_history_bulk_interval_missing_key_errors() {
    let server = TestServer::start("metric_hist_err").await;
    let res = gql(
        &server,
        "query Q { mlflowGetMetricHistoryBulkInterval(input: {runIds: [\"r\"]}) { metrics { key } } }",
        json!({}),
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    assert!(body["data"]["mlflowGetMetricHistoryBulkInterval"].is_null());
    assert!(body["errors"].as_array().unwrap()[0]
        .as_str()
        .unwrap()
        .contains("metric_key"));
}

// ===========================================================================
// Query.mlflowListArtifacts
// ===========================================================================

#[tokio::test]
async fn list_artifacts_returns_root_uri() {
    let server = TestServer::start("list_art").await;
    // The fixture run's artifact dir does not exist on disk; listing an absent
    // local dir returns an empty file list (matching the REST path), with the
    // run's artifact_uri echoed as rootUri.
    let res = gql(
        &server,
        "query Q { mlflowListArtifacts(input: {runId: \"f6f9b188dd2845c0ae79e10bce95d692\"}) { \
         rootUri files { path isDir fileSize } nextPageToken apiError } }",
        json!({}),
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    assert!(body["errors"].is_null(), "{}", res.text());
    let la = &body["data"]["mlflowListArtifacts"];
    assert!(la["rootUri"].as_str().unwrap().contains(FIXTURE_RUN_ID));
    assert!(la["files"].is_array());
    assert!(la["apiError"].is_null());
}

// ===========================================================================
// Query.mlflowSearchModelVersions (registry-backed)
// ===========================================================================

#[tokio::test]
async fn search_model_versions_returns_seeded_versions() {
    let server = TestServer::start("smv").await;
    // Seed a registered model + a version whose run_id matches the fixture run.
    server
        .registry
        .create_registered_model(WS, "gql_model", &[], None)
        .await
        .unwrap();
    server
        .registry
        .create_model_version(
            WS,
            "gql_model",
            "file:///tmp/src",
            Some(FIXTURE_RUN_ID),
            &[],
            None,
            None,
        )
        .await
        .unwrap();

    let res = gql(
        &server,
        "query Q($input: MlflowSearchModelVersionsInput!) { \
         mlflowSearchModelVersions(input: $input) { \
         modelVersions { name version runId creationTimestamp } nextPageToken apiError } }",
        json!({"input": {"filter": "name='gql_model'"}}),
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    assert!(body["errors"].is_null(), "{}", res.text());
    let mvs = body["data"]["mlflowSearchModelVersions"]["modelVersions"]
        .as_array()
        .unwrap();
    assert_eq!(mvs.len(), 1, "{}", res.text());
    assert_eq!(mvs[0]["name"], "gql_model");
    assert_eq!(mvs[0]["version"], "1");
    assert_eq!(mvs[0]["runId"], FIXTURE_RUN_ID);
    // creationTimestamp is a LongString → quoted int.
    assert!(mvs[0]["creationTimestamp"].is_string());
}

#[tokio::test]
async fn get_run_model_versions_extension_finds_seeded_version() {
    let server = TestServer::start("run_mv_ext").await;
    server
        .registry
        .create_registered_model(WS, "ext_model", &[], None)
        .await
        .unwrap();
    server
        .registry
        .create_model_version(
            WS,
            "ext_model",
            "file:///tmp/src",
            Some(FIXTURE_RUN_ID),
            &[],
            None,
            None,
        )
        .await
        .unwrap();

    let res = gql(
        &server,
        "query Q { mlflowGetRun(input: {runId: \"f6f9b188dd2845c0ae79e10bce95d692\"}) { \
         run { modelVersions { name version } } } }",
        json!({}),
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    assert!(body["errors"].is_null(), "{}", res.text());
    let mvs = body["data"]["mlflowGetRun"]["run"]["modelVersions"]
        .as_array()
        .unwrap();
    assert_eq!(mvs.len(), 1, "{}", res.text());
    assert_eq!(mvs[0]["name"], "ext_model");
}

// ===========================================================================
// Mutation.mlflowSearchRuns / mlflowSearchDatasets
// ===========================================================================

#[tokio::test]
async fn search_runs_mutation_returns_fixture_run() {
    let server = TestServer::start("search_runs").await;
    let res = gql(
        &server,
        "mutation M($input: MlflowSearchRunsInput!) { mlflowSearchRuns(input: $input) { \
         runs { info { runId experimentId } } nextPageToken apiError } }",
        json!({"input": {"experimentIds": [FIXTURE_EXP_ID]}}),
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    assert!(body["errors"].is_null(), "{}", res.text());
    let runs = body["data"]["mlflowSearchRuns"]["runs"].as_array().unwrap();
    assert_eq!(runs.len(), 1, "{}", res.text());
    assert_eq!(runs[0]["info"]["runId"], FIXTURE_RUN_ID);
}

#[tokio::test]
async fn search_datasets_requires_experiment_id() {
    let server = TestServer::start("search_ds_err").await;
    let res = gql(
        &server,
        "mutation M { mlflowSearchDatasets(input: {experimentIds: []}) { \
         datasetSummaries { name } } }",
        json!({}),
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    assert!(body["data"]["mlflowSearchDatasets"].is_null());
    assert!(body["errors"].as_array().unwrap()[0]
        .as_str()
        .unwrap()
        .contains("at least one experiment_id"));
}

#[tokio::test]
async fn search_datasets_returns_summaries() {
    let server = TestServer::start("search_ds").await;
    let res = gql(
        &server,
        "mutation M($input: MlflowSearchDatasetsInput!) { mlflowSearchDatasets(input: $input) { \
         datasetSummaries { experimentId name digest } apiError } }",
        json!({"input": {"experimentIds": [FIXTURE_EXP_ID]}}),
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    assert!(body["errors"].is_null(), "{}", res.text());
    assert!(body["data"]["mlflowSearchDatasets"]["datasetSummaries"].is_array());
}

// ===========================================================================
// test / testMutation echo fields
// ===========================================================================

#[tokio::test]
async fn test_query_echoes_input_string() {
    let server = TestServer::start("test_echo").await;
    let res = gql(
        &server,
        "query Q { test(inputString: \"hello\") { output } }",
        json!({}),
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    assert!(body["errors"].is_null(), "{}", res.text());
    assert_eq!(body["data"]["test"]["output"], "hello");
}

#[tokio::test]
async fn test_mutation_echoes_input_string() {
    let server = TestServer::start("test_mut_echo").await;
    let res = gql(
        &server,
        "mutation M { testMutation(inputString: \"world\") { output } }",
        json!({}),
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    assert_eq!(body["data"]["testMutation"]["output"], "world");
}

// ===========================================================================
// GET parses the body too (no query-string parsing)
// ===========================================================================

#[tokio::test]
async fn get_method_parses_json_body() {
    let server = TestServer::start("get_body").await;
    let body = json!({"query": "query Q { test(inputString: \"g\") { output } }"});
    // GET with a JSON body; content-type unchecked for GET.
    let res = send_raw(
        &server,
        Method::GET,
        Bytes::from(serde_json::to_vec(&body).unwrap()),
        true,
    )
    .await;
    assert_ok(&res);
    assert_eq!(res.json()["data"]["test"]["output"], "g");
}

// ===========================================================================
// Aliases + __typename
// ===========================================================================

#[tokio::test]
async fn field_alias_and_typename_are_honored() {
    let server = TestServer::start("alias_typename").await;
    let res = gql(
        &server,
        "query Q { r: mlflowGetRun(input: {runId: \"f6f9b188dd2845c0ae79e10bce95d692\"}) { \
         __typename run { info { __typename runId } } } }",
        json!({}),
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    assert!(body["errors"].is_null(), "{}", res.text());
    // Alias key present, field-name key absent.
    let r = &body["data"]["r"];
    assert_eq!(r["__typename"], "MlflowGetRunResponse");
    assert_eq!(r["run"]["info"]["__typename"], "MlflowRunInfo");
    assert_eq!(r["run"]["info"]["runId"], FIXTURE_RUN_ID);
    assert!(body["data"]["mlflowGetRun"].is_null());
}

// ===========================================================================
// No-batching / query-safety guard
// ===========================================================================

#[tokio::test]
async fn batched_array_body_is_rejected() {
    let server = TestServer::start("batched").await;
    let body = json!([
        {"query": "query { test(inputString: \"a\") { output } }"},
        {"query": "query { test(inputString: \"b\") { output } }"}
    ]);
    let res = send_raw(
        &server,
        Method::POST,
        Bytes::from(serde_json::to_vec(&body).unwrap()),
        true,
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    assert!(body["data"].is_null());
    assert!(body["errors"].as_array().unwrap()[0]
        .as_str()
        .unwrap()
        .contains("Batched GraphQL requests are not supported"));
}

#[tokio::test]
async fn missing_query_is_rejected() {
    let server = TestServer::start("no_query").await;
    let res = send_raw(
        &server,
        Method::POST,
        Bytes::from(serde_json::to_vec(&json!({"variables": {}})).unwrap()),
        true,
    )
    .await;
    assert_ok(&res);
    let body = res.json();
    assert!(body["data"].is_null());
    assert!(body["errors"].as_array().unwrap()[0]
        .as_str()
        .unwrap()
        .contains("Must provide query string"));
}

#[tokio::test]
async fn too_many_root_fields_is_rejected() {
    let server = TestServer::start("max_root").await;
    let fields = (0..12)
        .map(|i| format!("k_{i}: test(inputString: \"a\") {{ output }}"))
        .collect::<Vec<_>>()
        .join(" ");
    let res = gql(&server, &format!("query Q {{ {fields} }}"), json!({})).await;
    assert_ok(&res);
    let body = res.json();
    assert!(body["data"].is_null());
    let msg = body["errors"].as_array().unwrap()[0].as_str().unwrap();
    assert!(msg.contains("at most 10 root fields"), "{msg}");
    assert!(
        msg.contains("MLFLOW_SERVER_GRAPHQL_MAX_ROOT_FIELDS"),
        "{msg}"
    );
}

#[tokio::test]
async fn too_deep_query_is_rejected() {
    let server = TestServer::start("max_depth").await;
    let mut inner = String::from("name");
    for _ in 0..12 {
        inner = format!("name {{ {inner} }}");
    }
    let q = format!(
        "query Q {{ mlflowGetExperiment(input: {{experimentId: \"1\"}}) {{ experiment {{ {inner} }} }} }}"
    );
    let res = gql(&server, &q, json!({})).await;
    assert_ok(&res);
    let body = res.json();
    assert!(body["data"].is_null());
    assert_eq!(
        body["errors"].as_array().unwrap()[0],
        "Query exceeds maximum depth of 10"
    );
}

// ===========================================================================
// Content-type validation (POST only; MlflowException JSON, not in-band)
// ===========================================================================

#[tokio::test]
async fn post_without_content_type_is_mlflow_error() {
    let server = TestServer::start("no_ct").await;
    let body = json!({"query": "query Q { test(inputString: \"x\") { output } }"});
    // POST without content-type → `_validate_content_type` rejects *before*
    // GraphQL execution, so this is a normal MlflowException JSON error.
    let res = send_raw(
        &server,
        Method::POST,
        Bytes::from(serde_json::to_vec(&body).unwrap()),
        false,
    )
    .await;
    // Not an in-band 200 GraphQL body — it's a proper error response.
    assert_ne!(res.status, StatusCode::OK, "{}", res.text());
    let body = res.json();
    assert_eq!(body["error_code"], "INVALID_PARAMETER_VALUE");
    assert!(body["message"].as_str().unwrap().contains("Content-Type"));
}

// ===========================================================================
// T6.2 — schema parity
// ===========================================================================

/// The embedded SDL (`schema::SCHEMA_SDL`, `include_str!`) must be byte-identical
/// to the on-disk `autogenerated_schema.gql`, so the Rust server can never drift
/// from the Python graphene schema.
#[test]
fn embedded_sdl_matches_on_disk_gql() {
    let on_disk = std::fs::read_to_string(
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../../mlflow/server/js/src/graphql/autogenerated_schema.gql"),
    )
    .expect("read autogenerated_schema.gql");
    assert_eq!(
        mlflow_server::graphql::schema::SCHEMA_SDL,
        on_disk,
        "embedded GraphQL SDL drifted from autogenerated_schema.gql"
    );
}

/// Every implemented root field (Query + Mutation) must be declared in the SDL
/// under the corresponding root type, and every response `__typename` the
/// resolvers emit must be a type declared in the SDL.
#[test]
fn implemented_fields_present_in_schema() {
    let sdl = mlflow_server::graphql::schema::SCHEMA_SDL;

    // Extract a `type X { ... }` block body by name.
    fn type_block<'a>(sdl: &'a str, name: &str) -> &'a str {
        let head = format!("type {name} ");
        let start = sdl
            .find(&head)
            .unwrap_or_else(|| panic!("type {name} not found in SDL"));
        let open = sdl[start..].find('{').unwrap() + start;
        let mut depth = 0usize;
        for (i, c) in sdl[open..].char_indices() {
            match c {
                '{' => depth += 1,
                '}' => {
                    depth -= 1;
                    if depth == 0 {
                        return &sdl[open..open + i + 1];
                    }
                }
                _ => {}
            }
        }
        panic!("unterminated type {name} block");
    }

    let query_block = type_block(sdl, "Query");
    for field in mlflow_server::graphql::schema::IMPLEMENTED_QUERY_FIELDS {
        assert!(
            query_block.contains(&format!("{field}("))
                || query_block.contains(&format!("{field}:")),
            "Query.{field} missing from SDL"
        );
    }

    let mutation_block = type_block(sdl, "Mutation");
    for field in mlflow_server::graphql::schema::IMPLEMENTED_MUTATION_FIELDS {
        assert!(
            mutation_block.contains(&format!("{field}("))
                || mutation_block.contains(&format!("{field}:")),
            "Mutation.{field} missing from SDL"
        );
    }
}
