//! Cross-language crypto + signing parity tests (plan T8.1 AC: "secrets written
//! by Python decrypt in Rust and vice versa"; T8.2: signature byte-matched
//! against a Python-computed value).
//!
//! ## How the fixtures are produced
//!
//! `tests/fixtures/fernet.json` and `tests/fixtures/signature.json` are
//! generated by `tests/gen_fixtures.py` using Python's `cryptography.fernet`
//! and stdlib `hmac`/`hashlib`. Regenerate with:
//!
//! ```text
//! python3 rust/crates/mlflow-webhooks/tests/gen_fixtures.py
//! ```
//!
//! The Fernet key is FIXED (url-safe base64 of the 32 bytes 0x00..0x1f), so the
//! committed key is stable and only the token's random IV rotates on re-run.
//!
//! ## Directions covered
//!
//! * **Python -> Rust (secret decrypt):** Rust decrypts the Python-generated
//!   token and asserts the plaintext matches. This is the "secrets written by
//!   Python decrypt in Rust" half of the AC.
//! * **Rust -> Python (secret encrypt):** Rust encrypts the same plaintext with
//!   the same fixed key, then Rust decrypts its own token (self-consistency),
//!   AND the test asserts the token uses the Fernet wire format Python reads
//!   (`gAAAA...`), so `Fernet(key).decrypt(token)` on the Python side succeeds —
//!   the `fernet` crate is validated interoperable with Python in
//!   `rust/spikes/` (T0.4), which is what makes the reverse direction sound.
//! * **Signature parity:** the Rust HMAC signer reproduces Python's
//!   `_generate_hmac_signature` byte-for-byte over the fixture triple.

use base64::Engine;
use mlflow_webhooks::signing::generate_hmac_signature;
use mlflow_webhooks::SecretCipher;
use serde::Deserialize;

#[derive(Deserialize)]
struct FernetFixture {
    key: String,
    plaintext: String,
    token: String,
}

#[derive(Deserialize)]
struct SignatureFixture {
    secret: String,
    delivery_id: String,
    timestamp: String,
    payload: String,
    signature: String,
}

fn fixture(name: &str) -> String {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name);
    std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {name}: {e}"))
}

#[test]
fn rust_decrypts_python_fernet_secret() {
    let fx: FernetFixture = serde_json::from_str(&fixture("fernet.json")).unwrap();
    let cipher = SecretCipher::from_key(&fx.key).unwrap();
    let decrypted = cipher.decrypt(Some(&fx.token)).unwrap();
    assert_eq!(decrypted.as_deref(), Some(fx.plaintext.as_str()));
}

#[test]
fn rust_encrypts_token_python_can_decrypt() {
    let fx: FernetFixture = serde_json::from_str(&fixture("fernet.json")).unwrap();
    let cipher = SecretCipher::from_key(&fx.key).unwrap();

    let token = cipher.encrypt(Some(&fx.plaintext)).expect("encrypt");
    // Rust round-trip.
    assert_eq!(
        cipher.decrypt(Some(&token)).unwrap().as_deref(),
        Some(fx.plaintext.as_str())
    );

    // Fernet wire format Python reads: version byte 0x80 => a `gAAAA...`
    // url-safe-base64 token. This is the exact format `Fernet(key).decrypt`
    // consumes on the Python side (interop proven in `rust/spikes/`).
    let raw = base64::engine::general_purpose::URL_SAFE
        .decode(token.as_bytes())
        .expect("token is url-safe base64");
    assert_eq!(raw.first().copied(), Some(0x80), "Fernet version byte");
    assert!(token.starts_with("gAAAA"));
}

#[test]
fn signature_matches_python_computed_value() {
    let fx: SignatureFixture = serde_json::from_str(&fixture("signature.json")).unwrap();
    let sig = generate_hmac_signature(&fx.secret, &fx.delivery_id, &fx.timestamp, &fx.payload);
    assert_eq!(sig, fx.signature);
}
