"""Generate REPORT.md from ledger.json."""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent


def _table(headers: list[str], rows: list[list[Any]]) -> list[str]:
    def cell(value: Any) -> str:
        return str(value).replace("|", "\\|").replace("\n", " ")

    return [
        "| " + " | ".join(map(cell, headers)) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
        *("| " + " | ".join(map(cell, row)) + " |" for row in rows),
    ]


def _task_key(task: str) -> tuple[int, int]:
    phase, item = task.removeprefix("T").split(".")
    return int(phase), int(item)


def render(ledger: dict[str, Any]) -> str:
    items = ledger["items"]
    summary = ledger["summary"]
    blockers = ledger["license_blockers"]
    surface_count = sum(item["scope"] == "part_ii_surface" for item in items)
    module_count = sum(
        item["scope"] == "mlflow/genai" and item["symbol_kind"] == "module" for item in items
    )
    symbol_count = sum(
        item["scope"] == "mlflow/genai" and item["symbol_kind"] != "module" for item in items
    )
    lines = [
        "<!-- Generated by generate_report.py from ledger.json. Do not edit directly. -->",
        "# Part II GenAI inventory report",
        "",
        f"Reference: MLflow `{ledger['reference']['mlflow_version']}` at "
        f"`{ledger['reference']['git_sha']}`.",
        "",
        "## Blockers",
        "",
    ]
    if blockers:
        lines.extend(
            (
                f"- **BLOCKER — {blocker['name']}**: {blocker['license']}; "
                f"{blocker['reason']}. Resolution: {blocker['resolution']}."
            )
            for blocker in blockers
        )
    else:
        lines.append("None.")

    lines.extend([
        "",
        "## Coverage",
        "",
        f"The ledger contains {len(items):,} items: {module_count:,} `mlflow/genai` modules, "
        f"{symbol_count:,} definitions, and {surface_count:,} explicit Part II surface records. "
        f"Its test index contains {len(ledger['tests']):,} exact pytest test IDs.",
        "",
        *_table(
            ["Test execution classification", "Tests"],
            [
                [classification, summary["test_classification_counts"][classification]]
                for classification in ("server_reachable", "client_only", "python_internal")
            ],
        ),
        "",
        "`python_internal` tests exercise Python handlers, stores, workers, or monkeypatched "
        "implementation classes directly; they remain inventory evidence but are not falsely "
        "reported as repointable Rust HTTP conformance.",
        "",
        *_table(
            ["Classification", "Items"],
            [
                [classification, summary["classification_counts"][classification]]
                for classification in ("server_reachable", "client_only", "dead")
            ],
        ),
        "",
        "Conservative rule: ambiguous reachability is `server_reachable`. There are no "
        "unclassified items or server paths.",
        "",
        "## Server-reachable work allocation",
        "",
        *_table(
            ["Tier", "Items"],
            [[tier, summary["tier_counts"].get(tier, 0)] for tier in ("A", "B", "C")],
        ),
        "",
        *_table(
            ["Phase", "Items"],
            [
                [phase, count]
                for phase, count in sorted(
                    summary["phase_counts"].items(), key=lambda row: int(row[0][1:])
                )
            ],
        ),
        "",
        *_table(
            ["Task", "Items"],
            [
                [task, count]
                for task, count in sorted(
                    summary["task_counts"].items(), key=lambda row: _task_key(row[0])
                )
            ],
        ),
        "",
        "## Compatibility manifests",
        "",
        *_table(
            ["Manifest population", "Entries"],
            [[name, count] for name, count in sorted(ledger["manifest_counts"].items())],
        ),
        "",
        "The provider population is the union of the MLflow gateway registry, LiteLLM's "
        "provider list, and provider names present in the pinned wheel price snapshot. "
        "Each provider row records transform, limits, pricing, tokenizer, native-adapter, "
        "and LiteLLM-fallback presence.",
        "",
        "## License and provenance",
        "",
        *_table(
            ["Source", "Pin", "License", "Compatible"],
            [
                [
                    entry["source"],
                    entry["pin"],
                    entry["license"],
                    "yes" if entry["compatible"] else "NO — BLOCKER",
                ]
                for entry in ledger["license_audit"]
            ],
        ),
        "",
        "## Fixture and corpus strategy",
        "",
    ])
    item_strategies = Counter(item["fixture_oracle"]["strategy"] for item in items)
    oracle_strategies = Counter(oracle["strategy"] for oracle in ledger["fixture_oracles"].values())
    lines.extend([
        *_table(
            ["Strategy", "Ledger items", "Shared oracle groups"],
            [
                [strategy, item_strategies[strategy], oracle_strategies[strategy]]
                for strategy in ("existing_python_tests", "corpus recorder needed")
            ],
        ),
        "",
    ])
    for name, recorder in ledger["corpus_recorders"].items():
        lines.extend([
            f"### {name}",
            "",
            f"Entry points: {', '.join(f'`{entry}`' for entry in recorder['entry_points'])}.",
            "",
            f"Fixtures: `{recorder['fixture_root']}`. Normalization: {recorder['normalization']}.",
            "",
        ])

    ambiguities = Counter(item["ambiguity"] for item in items if item.get("ambiguity") is not None)
    lines.extend(["## Recorded ambiguities", ""])
    if ambiguities:
        lines.extend(f"- {text} ({count} surface records)" for text, count in ambiguities.items())
    else:
        lines.append("None.")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ledger = json.loads((HERE / "ledger.json").read_text())
    (HERE / "REPORT.md").write_text(render(ledger))


if __name__ == "__main__":
    main()
