"""Generate `mlflow-search`'s embedded sqlparse keyword table.

Run with:

    uv run --frozen python rust/tools/gen_keywords.py

The MLflow search-filter grammar is tokenized with `sqlparse`, whose lexer
classifies each bare word (`\\w[$#\\w]*`) by looking it up (uppercased) in a
merged set of dialect keyword dictionaries. A word that is a keyword lexes as
`Keyword` / `Keyword.Order` / `Name.Builtin` / ... instead of `Name`, which
changes how the token grouper builds Identifiers and Comparisons — and thus
which MLflow error (if any) fires. To reproduce that behavior exactly, we embed
the same merged table the default sqlparse lexer uses into
`src/keywords_generated.rs`.

Only the token *kinds* that affect grouping in our grammar are distinguished;
DML/DDL/DCL/CTE all collapse to `Keyword` (they group identically — as opaque
keywords). Regenerate whenever the pinned sqlparse version changes.
"""

from pathlib import Path

import sqlparse.keywords as kw

OUT = (
    Path(__file__).resolve().parents[1]
    / "crates"
    / "mlflow-search"
    / "src"
    / "keywords_generated.rs"
)

# Same order/set as sqlparse.lexer.Lexer.default_initialization.
DICTS = [
    kw.KEYWORDS_COMMON,
    kw.KEYWORDS_ORACLE,
    kw.KEYWORDS_MYSQL,
    kw.KEYWORDS_PLPGSQL,
    kw.KEYWORDS_HQL,
    kw.KEYWORDS_MSACCESS,
    kw.KEYWORDS_SNOWFLAKE,
    kw.KEYWORDS_BIGQUERY,
    kw.KEYWORDS,
]

VARIANT = {
    "Token.Keyword": "Keyword",
    "Token.Keyword.Order": "KeywordOrder",
    "Token.Keyword.DML": "Keyword",
    "Token.Keyword.DDL": "Keyword",
    "Token.Keyword.DCL": "Keyword",
    "Token.Keyword.CTE": "Keyword",
    "Token.Name.Builtin": "NameBuiltin",
    "Token.Operator": "Operator",
    "Token.Name": "Name",
}


def main():
    # sqlparse's `Lexer.is_keyword` looks up the uppercased word in each dict in
    # the order they were added and returns the FIRST match (see
    # `add_keywords` / `is_keyword`). So we must replicate first-wins, not a
    # last-wins `dict.update` merge (e.g. TIMESTAMP is Name.Builtin in
    # KEYWORDS_HQL, which is added before KEYWORDS where it is a plain Keyword).
    merged = {}
    for d in DICTS:
        for key, ttype in d.items():
            merged.setdefault(key, ttype)

    lines = [
        "// @generated by rust/tools/gen_keywords.py from sqlparse's merged",
        "// KEYWORDS dicts (the default-lexer dialect set). DO NOT EDIT BY HAND.",
        "//",
        "// Lookup is on the UPPERCASED word (sqlparse uppercases before lookup).",
        "// Maps a bare `\\w[$#\\w]*` word to the sqlparse token kind it lexes as;",
        "// words absent here fall through to `TokenKind::Name`. The slice is sorted",
        "// by key so the lexer can binary-search it.",
        "use crate::token::KeywordKind;",
        "",
        "pub(crate) static KEYWORDS: &[(&str, KeywordKind)] = &[",
    ]
    for name, ttype in sorted(merged.items(), key=lambda kv: kv[0]):
        variant = VARIANT[str(ttype)]
        key = name.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    ("{key}", KeywordKind::{variant}),')
    lines.append("];")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(merged)} keywords)")  # noqa: T201


if __name__ == "__main__":
    main()
