//! Byte-for-byte golden parity test against the real Python implementation.
//!
//! Fixtures in `tests/goldens/*.json` are generated by
//! `rust/tools/gen_error_goldens.py`, which drives the actual
//! `mlflow.exceptions.MlflowException` / `_not_implemented` / auth
//! response-building code (never a re-implementation) and records the exact
//! response bytes. Regenerate with:
//!
//! ```sh
//! uv run --frozen python rust/tools/gen_error_goldens.py
//! ```

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

use axum::response::{IntoResponse, Response};
use http_body_util::BodyExt;
use mlflow_error::{
    forbidden_response, not_implemented_response, unauthenticated_response, ErrorCode, MlflowError,
};
use serde::Deserialize;

#[derive(Deserialize)]
struct GoldenCase {
    name: String,
    status: u16,
    content_type: String,
    body: String,
    headers: HashMap<String, String>,
}

fn goldens_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/goldens")
}

fn load_golden(name: &str) -> GoldenCase {
    let path = goldens_dir().join(format!("{name}.json"));
    let raw = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read golden fixture {}: {e}", path.display()));
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()))
}

async fn assert_response_matches_golden(response: Response, golden: &GoldenCase) {
    assert_eq!(
        response.status().as_u16(),
        golden.status,
        "status mismatch for {}",
        golden.name
    );

    let actual_content_type = response
        .headers()
        .get(axum::http::header::CONTENT_TYPE)
        .map(|v| v.to_str().unwrap().to_string())
        .unwrap_or_default();
    assert_eq!(
        actual_content_type, golden.content_type,
        "content-type mismatch for {}",
        golden.name
    );

    for (header_name, expected_value) in &golden.headers {
        let actual_value = response
            .headers()
            .get(header_name.as_str())
            .unwrap_or_else(|| panic!("missing header {header_name} for {}", golden.name))
            .to_str()
            .unwrap();
        assert_eq!(
            actual_value, expected_value,
            "header {header_name} mismatch for {}",
            golden.name
        );
    }

    let body_bytes = response.into_body().collect().await.unwrap().to_bytes();
    let body_str = String::from_utf8(body_bytes.to_vec()).unwrap();
    assert_eq!(body_str, golden.body, "body mismatch for {}", golden.name);
}

#[tokio::test]
async fn resource_does_not_exist_matches_python() {
    let golden = load_golden("resource_does_not_exist");
    let err = MlflowError::resource_does_not_exist("Run 'nonexistent-run-id' not found");
    assert_response_matches_golden(err.into_response(), &golden).await;
}

#[tokio::test]
async fn invalid_parameter_value_matches_python() {
    let golden = load_golden("invalid_parameter_value");
    let err = MlflowError::invalid_parameter_value(
        "Invalid value for parameter 'max_results': must be positive",
    );
    assert_response_matches_golden(err.into_response(), &golden).await;
}

#[tokio::test]
async fn internal_error_matches_python() {
    let golden = load_golden("internal_error");
    let err = MlflowError::internal_error("Unexpected internal error");
    assert_response_matches_golden(err.into_response(), &golden).await;
}

#[tokio::test]
async fn unauthenticated_mlflow_exception_matches_python() {
    let golden = load_golden("unauthenticated_mlflow_exception");
    let err = MlflowError::new("Not authenticated", ErrorCode::Unauthenticated);
    assert_response_matches_golden(err.into_response(), &golden).await;
}

#[tokio::test]
async fn permission_denied_mlflow_exception_matches_python() {
    let golden = load_golden("permission_denied_mlflow_exception");
    let err = MlflowError::permission_denied("Permission denied");
    assert_response_matches_golden(err.into_response(), &golden).await;
}

#[tokio::test]
async fn not_implemented_404_matches_python() {
    let golden = load_golden("not_implemented_404");
    assert_response_matches_golden(not_implemented_response(), &golden).await;
}

#[tokio::test]
async fn unauthenticated_401_matches_python() {
    let golden = load_golden("unauthenticated_401");
    assert_response_matches_golden(unauthenticated_response(), &golden).await;
}

#[tokio::test]
async fn auth_forbidden_403_matches_python() {
    let golden = load_golden("auth_forbidden_403");
    assert_response_matches_golden(forbidden_response(), &golden).await;
}
