//! Root-field resolvers — the Rust analogue of the graphene `QueryType` /
//! `MutationType` `resolve_*` methods (`autogenerated_graphql_schema.py`,
//! `graphql_schema_extensions.py`).
//!
//! Each resolver reads its `input` object (already substituted for query
//! variables by the executor), calls the same store method the corresponding
//! REST handler uses, and builds the response as a fully-materialized [`GqlVal`]
//! object carrying *every* schema field (graphene's default resolver reads
//! proto scalar defaults, so unset scalar fields serialize as `""` / `0`, not
//! null; only message-typed fields are null when absent). The executor then
//! projects the query's selection set onto that object.
//!
//! ## Field-value fidelity
//!
//! * `LongString` fields (timestamps, steps, file sizes) → [`GqlVal::Long`],
//!   which serializes as `str(long)` — a *quoted* integer.
//! * `Float` fields (metric values) → [`GqlVal::Float`], Python-float-repr, and
//!   NaN → GraphQL null (`MlflowMetricExtension.resolve_value`,
//!   `graphql_schema_extensions.py:68`).
//! * Enum fields (`status`) → the enum *name* string
//!   (`MlflowRunStatus` / `MlflowModelVersionStatus`).
//! * `apiError` → always null (OSS impls never populate it — see the executor
//!   module docs).
//!
//! ## `MlflowGetRun` extension resolvers
//!
//! `MlflowRunExtension` (`graphql_schema_extensions.py:44`) adds two derived
//! fields resolved with *further* store calls: `experiment` (via
//! `get_experiment_impl` on the run's `experiment_id`) and `modelVersions` (via
//! `search_model_versions_impl` with `filter="run_id='<run_id>'"`). Both are
//! resolved eagerly here so the projected object has them available; a resolver
//! error there surfaces the same way (the whole root field errors).

use mlflow_error::MlflowError;
use mlflow_store::{
    Dataset, DatasetInput, DatasetSummary, Experiment, ExperimentTag, Metric, MetricWithRunId,
    Param, Run, RunData, RunInfo, RunInputs, RunOutputs, RunTag, RunsPage, ViewType,
};

use super::value::GqlVal;
use crate::state::AppState;
use crate::workspace::Workspace;

/// Read a required, non-empty string field from a resolver input, mirroring the
/// REST handlers' `_assert_required` message. GraphQL inputs are optional at the
/// schema level, so an absent/empty value reproduces the same store-facing error
/// the REST path would raise.
fn input_str<'a>(input: &'a ResolverInput, key: &str) -> Option<&'a str> {
    input.get(key).and_then(|v| v.as_str())
}

type ResolverInput = serde_json::Map<String, serde_json::Value>;

// ---------------------------------------------------------------------------
// Query.mlflowGetExperiment
// ---------------------------------------------------------------------------

/// `resolve_mlflow_get_experiment` → `get_experiment_impl`.
pub async fn get_experiment(
    state: &AppState,
    ws: &Workspace,
    input: &ResolverInput,
) -> Result<GqlVal, MlflowError> {
    let experiment_id = require(input_str(input, "experimentId"), "experiment_id")?;
    let exp = state
        .tracking_store()
        .get_experiment(ws.name(), experiment_id)
        .await?;
    Ok(get_experiment_response(Some(exp)))
}

fn get_experiment_response(exp: Option<Experiment>) -> GqlVal {
    GqlVal::object(
        "GetExperimentResponse",
        vec![
            ("experiment", exp.map(experiment).unwrap_or(GqlVal::Null)),
            ("apiError", GqlVal::Null),
        ],
    )
}

fn experiment(exp: Experiment) -> GqlVal {
    GqlVal::object(
        "Experiment",
        vec![
            ("experimentId", GqlVal::str(exp.experiment_id)),
            ("name", GqlVal::str(exp.name)),
            (
                "artifactLocation",
                GqlVal::str(exp.artifact_location.unwrap_or_default()),
            ),
            ("lifecycleStage", GqlVal::str(exp.lifecycle_stage)),
            ("lastUpdateTime", GqlVal::Long(exp.last_update_time.unwrap_or(0))),
            ("creationTime", GqlVal::Long(exp.creation_time.unwrap_or(0))),
            (
                "tags",
                GqlVal::List(exp.tags.into_iter().map(experiment_tag).collect()),
            ),
            // Unset proto2 optional strings read as "" via graphene's default
            // resolver (the impl leaves them unset). The Python test accepts
            // `in (None, "")`; graphene yields "".
            ("effectiveTraceArchivalRetention", GqlVal::str("")),
            ("workspace", GqlVal::str("")),
        ],
    )
}

fn experiment_tag(tag: ExperimentTag) -> GqlVal {
    GqlVal::object(
        "ExperimentTag",
        vec![
            ("key", GqlVal::str(tag.key)),
            ("value", GqlVal::str(tag.value.unwrap_or_default())),
        ],
    )
}

// ---------------------------------------------------------------------------
// Query.mlflowGetRun  (MlflowRunExtension)
// ---------------------------------------------------------------------------

/// `resolve_mlflow_get_run` → `get_run_impl`, with the `MlflowRunExtension`
/// derived fields (`experiment`, `modelVersions`) resolved eagerly.
pub async fn get_run(
    state: &AppState,
    ws: &Workspace,
    input: &ResolverInput,
) -> Result<GqlVal, MlflowError> {
    // `run_id or run_uuid` (REST parity), then `_assert_required`.
    let run_id = input_str(input, "runId")
        .filter(|s| !s.is_empty())
        .or_else(|| input_str(input, "runUuid").filter(|s| !s.is_empty()));
    let run_id = require(run_id, "run_id")?;

    let run = state.tracking_store().get_run(ws.name(), run_id).await?;
    let run_val = run_extension(state, ws, run).await?;
    Ok(GqlVal::object(
        "GetRunResponse",
        vec![("run", run_val), ("apiError", GqlVal::Null)],
    ))
}

/// Build a `MlflowRunExtension`: the base run fields plus the two derived fields.
async fn run_extension(
    state: &AppState,
    ws: &Workspace,
    run: Run,
) -> Result<GqlVal, MlflowError> {
    let experiment_id = run.info.experiment_id.clone();
    let run_id = run.info.run_id.clone();

    let mut fields = run_base_fields(run);

    // `resolve_experiment`: get_experiment_impl on the run's experiment_id.
    let exp = state
        .tracking_store()
        .get_experiment(ws.name(), &experiment_id)
        .await?;
    fields.push(("experiment", experiment(exp)));

    // `resolve_model_versions`: search_model_versions with filter run_id='...'.
    let model_versions = resolve_model_versions_for_run(state, ws, &run_id).await?;
    fields.push(("modelVersions", model_versions));

    Ok(GqlVal::object("Run", fields))
}

/// The base `MlflowRun` fields (`info`/`data`/`inputs`/`outputs`).
fn run_base_fields(run: Run) -> Vec<(&'static str, GqlVal)> {
    vec![
        ("info", run_info(run.info)),
        ("data", run_data(run.data)),
        ("inputs", run_inputs(run.inputs)),
        ("outputs", run_outputs(run.outputs)),
    ]
}

fn run_info(info: RunInfo) -> GqlVal {
    let run_id = info.run_id.clone();
    GqlVal::object(
        "RunInfo",
        vec![
            ("runId", GqlVal::str(run_id.clone())),
            ("runUuid", GqlVal::str(run_id)),
            ("runName", GqlVal::str(info.run_name)),
            ("experimentId", GqlVal::str(info.experiment_id)),
            ("userId", GqlVal::str(info.user_id.unwrap_or_default())),
            ("status", GqlVal::str(info.status)),
            ("startTime", GqlVal::Long(info.start_time.unwrap_or(0))),
            ("endTime", GqlVal::Long(info.end_time.unwrap_or(0))),
            (
                "artifactUri",
                GqlVal::str(info.artifact_uri.unwrap_or_default()),
            ),
            ("lifecycleStage", GqlVal::str(info.lifecycle_stage)),
        ],
    )
}

fn run_data(data: RunData) -> GqlVal {
    GqlVal::object(
        "RunData",
        vec![
            (
                "metrics",
                GqlVal::List(data.metrics.into_iter().map(metric_extension).collect()),
            ),
            (
                "params",
                GqlVal::List(data.params.into_iter().map(param).collect()),
            ),
            (
                "tags",
                GqlVal::List(data.tags.into_iter().map(run_tag).collect()),
            ),
        ],
    )
}

/// `MlflowMetricExtension`: the base metric fields, with `value` mapping NaN to
/// GraphQL null (`resolve_value`). Run-data metrics carry no dataset/model/run
/// id (proto defaults ""/absent), matching `RunData.to_proto`.
fn metric_extension(m: Metric) -> GqlVal {
    GqlVal::object(
        "Metric",
        vec![
            ("key", GqlVal::str(m.key)),
            ("value", float_or_null(m.value)),
            ("timestamp", GqlVal::Long(m.timestamp)),
            ("step", GqlVal::Long(m.step)),
            ("datasetName", GqlVal::str("")),
            ("datasetDigest", GqlVal::str("")),
            ("modelId", GqlVal::str("")),
            ("runId", GqlVal::str("")),
        ],
    )
}

fn param(p: Param) -> GqlVal {
    GqlVal::object(
        "Param",
        vec![
            ("key", GqlVal::str(p.key)),
            ("value", GqlVal::str(p.value)),
        ],
    )
}

fn run_tag(t: RunTag) -> GqlVal {
    GqlVal::object(
        "RunTag",
        vec![
            ("key", GqlVal::str(t.key)),
            ("value", GqlVal::str(t.value)),
        ],
    )
}

fn run_inputs(inputs: RunInputs) -> GqlVal {
    GqlVal::object(
        "RunInputs",
        vec![
            (
                "datasetInputs",
                GqlVal::List(inputs.dataset_inputs.into_iter().map(dataset_input).collect()),
            ),
            (
                "modelInputs",
                GqlVal::List(
                    inputs
                        .model_inputs
                        .into_iter()
                        .map(|mi| {
                            GqlVal::object("ModelInput", vec![("modelId", GqlVal::str(mi.model_id))])
                        })
                        .collect(),
                ),
            ),
        ],
    )
}

fn dataset_input(di: DatasetInput) -> GqlVal {
    GqlVal::object(
        "DatasetInput",
        vec![
            (
                "tags",
                GqlVal::List(
                    di.tags
                        .into_iter()
                        .map(|t| {
                            GqlVal::object(
                                "InputTag",
                                vec![
                                    ("key", GqlVal::str(t.key)),
                                    ("value", GqlVal::str(t.value)),
                                ],
                            )
                        })
                        .collect(),
                ),
            ),
            ("dataset", dataset(di.dataset)),
        ],
    )
}

/// `MlflowDataset`: `schema`/`profile` are proto2 optional strings the store may
/// leave as `None`; graphene reads the scalar default `""` when unset.
fn dataset(d: Dataset) -> GqlVal {
    GqlVal::object(
        "Dataset",
        vec![
            ("name", GqlVal::str(d.name)),
            ("digest", GqlVal::str(d.digest)),
            ("sourceType", GqlVal::str(d.source_type)),
            ("source", GqlVal::str(d.source)),
            ("schema", GqlVal::str(d.schema.unwrap_or_default())),
            ("profile", GqlVal::str(d.profile.unwrap_or_default())),
        ],
    )
}

fn run_outputs(outputs: RunOutputs) -> GqlVal {
    GqlVal::object(
        "RunOutputs",
        vec![(
            "modelOutputs",
            GqlVal::List(
                outputs
                    .model_outputs
                    .into_iter()
                    .map(|mo| {
                        GqlVal::object(
                            "ModelOutput",
                            vec![
                                ("modelId", GqlVal::str(mo.model_id)),
                                ("step", GqlVal::Long(mo.step)),
                            ],
                        )
                    })
                    .collect(),
            ),
        )],
    )
}

// ---------------------------------------------------------------------------
// Query.mlflowGetMetricHistoryBulkInterval
// ---------------------------------------------------------------------------

/// `resolve_mlflow_get_metric_history_bulk_interval` →
/// `get_metric_history_bulk_interval_impl`. Reuses the same validation the REST
/// handler applies (run-id count bounds, metric_key required, step-range
/// coherence, max_results bounds).
pub async fn get_metric_history_bulk_interval(
    state: &AppState,
    ws: &Workspace,
    input: &ResolverInput,
) -> Result<GqlVal, MlflowError> {
    use mlflow_store::{MAX_RESULTS_PER_RUN, MAX_RUNS_GET_METRIC_HISTORY_BULK};

    let run_ids: Vec<String> = input
        .get("runIds")
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str().map(str::to_string))
                .collect()
        })
        .unwrap_or_default();
    if run_ids.is_empty() {
        return Err(missing_required("run_ids"));
    }
    if run_ids.len() > MAX_RUNS_GET_METRIC_HISTORY_BULK {
        return Err(MlflowError::invalid_parameter_value(format!(
            "GetMetricHistoryBulkInterval request must specify at most \
             {MAX_RUNS_GET_METRIC_HISTORY_BULK} run_ids. Received {} run_ids.",
            run_ids.len()
        )));
    }
    let metric_key = require(input_str(input, "metricKey"), "metric_key")?;

    let start_step = input.get("startStep").and_then(serde_json::Value::as_i64);
    let end_step = input.get("endStep").and_then(serde_json::Value::as_i64);
    let (start_step, end_step) = match (start_step, end_step) {
        (Some(s), Some(e)) => {
            if s > e {
                return Err(MlflowError::invalid_parameter_value(format!(
                    "end_step must be greater than start_step. \
                     Found start_step={s} and end_step={e}."
                )));
            }
            (Some(s), Some(e))
        }
        (None, None) => (None, None),
        _ => {
            return Err(MlflowError::invalid_parameter_value(
                "If either start step or end step are specified, both must be specified."
                    .to_string(),
            ));
        }
    };

    let max_results = match input.get("maxResults").and_then(serde_json::Value::as_i64) {
        Some(mr) => {
            if !(1..=MAX_RESULTS_PER_RUN as i64).contains(&mr) {
                return Err(MlflowError::invalid_parameter_value(format!(
                    "max_results must be between 1 and {MAX_RESULTS_PER_RUN}. \
                     See the API docs for more information about request parameters."
                )));
            }
            mr as usize
        }
        None => MAX_RESULTS_PER_RUN,
    };

    let run_id_refs: Vec<&str> = run_ids.iter().map(String::as_str).collect();
    let metrics = state
        .tracking_store()
        .get_metric_history_bulk_interval(
            ws.name(),
            &run_id_refs,
            metric_key,
            max_results,
            start_step,
            end_step,
        )
        .await?;

    Ok(GqlVal::object(
        "GetMetricHistoryBulkIntervalResponse",
        vec![
            (
                "metrics",
                GqlVal::List(metrics.into_iter().map(metric_with_run_id).collect()),
            ),
            ("apiError", GqlVal::Null),
        ],
    ))
}

fn metric_with_run_id(m: MetricWithRunId) -> GqlVal {
    GqlVal::object(
        "MetricWithRunId",
        vec![
            ("key", GqlVal::str(m.metric.key)),
            ("value", float_or_null(m.metric.value)),
            ("timestamp", GqlVal::Long(m.metric.timestamp)),
            ("step", GqlVal::Long(m.metric.step)),
            ("runId", GqlVal::str(m.run_id)),
        ],
    )
}

// ---------------------------------------------------------------------------
// Query.mlflowListArtifacts
// ---------------------------------------------------------------------------

/// `resolve_mlflow_list_artifacts` → `list_artifacts_impl`. Resolves the run's
/// artifact root, lists at the (validated) path, and shapes the response.
pub async fn list_artifacts(
    state: &AppState,
    ws: &Workspace,
    input: &ResolverInput,
) -> Result<GqlVal, MlflowError> {
    let run_id = input_str(input, "runId")
        .filter(|s| !s.is_empty())
        .or_else(|| input_str(input, "runUuid").filter(|s| !s.is_empty()));
    let run_id = require(run_id, "run_id")?;

    let path = input_str(input, "path").filter(|s| !s.is_empty());
    let validated = match path {
        Some(p) => Some(mlflow_artifacts::validate_path_is_safe(p)?),
        None => None,
    };

    let run = state.tracking_store().get_run(ws.name(), run_id).await?;
    let artifact_uri = run.info.artifact_uri.unwrap_or_default();
    let files =
        crate::artifacts::list_artifacts_at(state, &artifact_uri, validated.as_deref()).await?;

    let file_vals = files
        .into_iter()
        .map(|f| {
            GqlVal::object(
                "FileInfo",
                vec![
                    ("path", GqlVal::str(f.path.unwrap_or_default())),
                    ("isDir", GqlVal::Bool(f.is_dir.unwrap_or(false))),
                    ("fileSize", GqlVal::Long(f.file_size.unwrap_or(0))),
                ],
            )
        })
        .collect();

    Ok(GqlVal::object(
        "ListArtifactsResponse",
        vec![
            ("rootUri", GqlVal::str(artifact_uri)),
            ("files", GqlVal::List(file_vals)),
            // `next_page_token` unset (proto2 optional string) → "".
            ("nextPageToken", GqlVal::str("")),
            ("apiError", GqlVal::Null),
        ],
    ))
}

// ---------------------------------------------------------------------------
// Query.mlflowSearchModelVersions  /  MlflowRunExtension.modelVersions
// ---------------------------------------------------------------------------

/// `resolve_mlflow_search_model_versions` → `search_model_versions_impl`.
pub async fn search_model_versions(
    state: &AppState,
    ws: &Workspace,
    input: &ResolverInput,
) -> Result<GqlVal, MlflowError> {
    let filter = input_str(input, "filter").filter(|s| !s.is_empty());
    // `max_results` is a `LongString` input → arrives as a JSON string or int;
    // absent → the proto default 200000 (the store default; §3.14 note).
    let max_results = input
        .get("maxResults")
        .and_then(long_string_to_i64)
        .unwrap_or(SEARCH_MODEL_VERSIONS_DEFAULT_MAX_RESULTS);
    let order_by = string_list(input, "orderBy");
    let page_token = input_str(input, "pageToken").filter(|s| !s.is_empty());

    let page = state
        .registry_store()?
        .search_model_versions(ws.name(), filter, max_results, &order_by, page_token)
        .await?;

    let mvs = page
        .model_versions
        .into_iter()
        .map(model_version)
        .collect();
    Ok(GqlVal::object(
        "SearchModelVersionsResponse",
        vec![
            ("modelVersions", GqlVal::List(mvs)),
            (
                "nextPageToken",
                GqlVal::str(page.next_page_token.unwrap_or_default()),
            ),
            ("apiError", GqlVal::Null),
        ],
    ))
}

/// `SearchModelVersions.max_results` proto default (`model_registry.proto:744`).
/// Python passes `request_message.max_results` straight to the store, so an
/// omitted GraphQL `maxResults` uses the proto scalar default.
const SEARCH_MODEL_VERSIONS_DEFAULT_MAX_RESULTS: i64 = 200_000;

/// `MlflowRunExtension.resolve_model_versions`: search with `run_id='<id>'`, no
/// pagination args (proto default max_results applies).
async fn resolve_model_versions_for_run(
    state: &AppState,
    ws: &Workspace,
    run_id: &str,
) -> Result<GqlVal, MlflowError> {
    let filter = format!("run_id='{run_id}'");
    let page = state
        .registry_store()?
        .search_model_versions(
            ws.name(),
            Some(&filter),
            SEARCH_MODEL_VERSIONS_DEFAULT_MAX_RESULTS,
            &[],
            None,
        )
        .await?;
    Ok(GqlVal::List(
        page.model_versions.into_iter().map(model_version).collect(),
    ))
}

fn model_version(mv: mlflow_registry::ModelVersion) -> GqlVal {
    GqlVal::object(
        "ModelVersion",
        vec![
            ("name", GqlVal::str(mv.name)),
            ("version", GqlVal::str(mv.version)),
            (
                "creationTimestamp",
                GqlVal::Long(mv.creation_timestamp.unwrap_or(0)),
            ),
            (
                "lastUpdatedTimestamp",
                GqlVal::Long(mv.last_updated_timestamp.unwrap_or(0)),
            ),
            ("userId", GqlVal::str(mv.user_id.unwrap_or_default())),
            (
                "currentStage",
                GqlVal::str(mv.current_stage.unwrap_or_default()),
            ),
            ("description", GqlVal::str(mv.description.unwrap_or_default())),
            ("source", GqlVal::str(mv.source.unwrap_or_default())),
            ("runId", GqlVal::str(mv.run_id.unwrap_or_default())),
            ("status", GqlVal::str(mv.status.unwrap_or_default())),
            (
                "statusMessage",
                GqlVal::str(mv.status_message.unwrap_or_default()),
            ),
            (
                "tags",
                GqlVal::List(
                    mv.tags
                        .into_iter()
                        .map(|t| {
                            GqlVal::object(
                                "ModelVersionTag",
                                vec![
                                    ("key", GqlVal::str(t.key)),
                                    ("value", GqlVal::str(t.value.unwrap_or_default())),
                                ],
                            )
                        })
                        .collect(),
                ),
            ),
            ("runLink", GqlVal::str(mv.run_link.unwrap_or_default())),
            (
                "aliases",
                GqlVal::List(mv.aliases.into_iter().map(GqlVal::Str).collect()),
            ),
            // `model_id` / `model_params` / `model_metrics` / `deployment_job_state`
            // are not populated by the OSS search path (message-typed / repeated
            // fields absent → null / empty).
            ("modelId", GqlVal::str("")),
            ("modelParams", GqlVal::List(Vec::new())),
            ("modelMetrics", GqlVal::List(Vec::new())),
            ("deploymentJobState", GqlVal::Null),
        ],
    )
}

// ---------------------------------------------------------------------------
// Mutation.mlflowSearchRuns
// ---------------------------------------------------------------------------

/// `resolve_mlflow_search_runs` → `search_runs_impl`. A mutation in name only —
/// it delegates to the same read logic. Each run is an `MlflowRunExtension`
/// (with derived `experiment`/`modelVersions`).
pub async fn search_runs(
    state: &AppState,
    ws: &Workspace,
    input: &ResolverInput,
) -> Result<GqlVal, MlflowError> {
    let experiment_ids = string_list(input, "experimentIds");
    let filter = input_str(input, "filter").filter(|s| !s.is_empty());
    let run_view_type = match input.get("runViewType").and_then(|v| v.as_str()) {
        Some("DELETED_ONLY") => ViewType::DeletedOnly,
        Some("ALL") => ViewType::All,
        _ => ViewType::ActiveOnly,
    };
    // `max_results` proto default 1000 (SearchRuns).
    let max_results = input
        .get("maxResults")
        .and_then(serde_json::Value::as_i64)
        .unwrap_or(1000);
    let order_by = string_list(input, "orderBy");
    let page_token = input_str(input, "pageToken").filter(|s| !s.is_empty());

    let RunsPage {
        runs,
        next_page_token,
    } = state
        .tracking_store()
        .search_runs(
            ws.name(),
            &experiment_ids,
            filter,
            run_view_type,
            Some(max_results),
            &order_by,
            page_token,
        )
        .await?;

    let mut run_vals = Vec::with_capacity(runs.len());
    for run in runs {
        run_vals.push(run_extension(state, ws, run).await?);
    }

    Ok(GqlVal::object(
        "SearchRunsResponse",
        vec![
            ("runs", GqlVal::List(run_vals)),
            (
                "nextPageToken",
                GqlVal::str(next_page_token.unwrap_or_default()),
            ),
            ("apiError", GqlVal::Null),
        ],
    ))
}

// ---------------------------------------------------------------------------
// Mutation.mlflowSearchDatasets
// ---------------------------------------------------------------------------

/// `resolve_mlflow_search_datasets` → `search_datasets_impl`.
pub async fn search_datasets(
    state: &AppState,
    ws: &Workspace,
    input: &ResolverInput,
) -> Result<GqlVal, MlflowError> {
    const MAX_EXPERIMENT_IDS: usize = 20;
    let experiment_ids = string_list(input, "experimentIds");
    if experiment_ids.is_empty() {
        return Err(MlflowError::invalid_parameter_value(
            "SearchDatasets request must specify at least one experiment_id.".to_string(),
        ));
    }
    if experiment_ids.len() > MAX_EXPERIMENT_IDS {
        return Err(MlflowError::invalid_parameter_value(format!(
            "SearchDatasets request cannot specify more than {MAX_EXPERIMENT_IDS} \
             experiment_ids. Received {} experiment_ids.",
            experiment_ids.len()
        )));
    }
    let ids: Vec<&str> = experiment_ids.iter().map(String::as_str).collect();
    let summaries = state
        .tracking_store()
        .search_datasets(ws.name(), &ids)
        .await?;

    Ok(GqlVal::object(
        "SearchDatasetsResponse",
        vec![
            (
                "datasetSummaries",
                GqlVal::List(summaries.into_iter().map(dataset_summary).collect()),
            ),
            ("apiError", GqlVal::Null),
        ],
    ))
}

fn dataset_summary(s: DatasetSummary) -> GqlVal {
    GqlVal::object(
        "DatasetSummary",
        vec![
            ("experimentId", GqlVal::str(s.experiment_id)),
            ("name", GqlVal::str(s.name)),
            ("digest", GqlVal::str(s.digest)),
            // `context` is an optional string on the summary; unset → "".
            ("context", GqlVal::str(s.context.unwrap_or_default())),
        ],
    )
}

// ---------------------------------------------------------------------------
// Query.test / Mutation.testMutation (echo fields)
// ---------------------------------------------------------------------------

/// `resolve_test` / `resolve_test_mutation`: echo `input_string` into `output`.
pub fn test_echo(tag: &'static str, input: &ResolverInput) -> GqlVal {
    let output = input
        .get("inputString")
        .and_then(|v| v.as_str())
        .map(str::to_string);
    GqlVal::object(tag, vec![("output", GqlVal::opt_str(output))])
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// A `Float` value, mapping NaN to GraphQL null
/// (`MlflowMetricExtension.resolve_value`).
fn float_or_null(v: f64) -> GqlVal {
    if v.is_nan() {
        GqlVal::Null
    } else {
        GqlVal::Float(v)
    }
}

/// A `[String]` input argument as a `Vec<String>` (absent → empty).
fn string_list(input: &ResolverInput, key: &str) -> Vec<String> {
    input
        .get(key)
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str().map(str::to_string))
                .collect()
        })
        .unwrap_or_default()
}

/// Coerce a `LongString` JSON value (string or int) to `i64`.
fn long_string_to_i64(v: &serde_json::Value) -> Option<i64> {
    match v {
        serde_json::Value::String(s) => s.parse::<i64>().ok(),
        serde_json::Value::Number(n) => n.as_i64(),
        _ => None,
    }
}

fn require<'a>(value: Option<&'a str>, param: &str) -> Result<&'a str, MlflowError> {
    match value {
        Some(v) if !v.is_empty() => Ok(v),
        _ => Err(missing_required(param)),
    }
}

fn missing_required(param: &str) -> MlflowError {
    MlflowError::invalid_parameter_value(format!(
        "Missing value for required parameter '{param}'. \
         See the API docs for more information about request parameters."
    ))
}
