//! The GraphQL schema (SDL) source of truth and the object-type name map.
//!
//! ## Single source of truth (T6.2)
//!
//! The schema is embedded verbatim from the repo's autogenerated SDL,
//! `mlflow/server/js/src/graphql/autogenerated_schema.gql` — the same file the
//! Python graphene schema is generated from (`dev/proto_to_graphql/`). It is
//! pulled in at compile time with [`include_str!`] using a path relative to this
//! file, so the Rust-served schema and the Python schema can never drift: the
//! T6.2 schema-diff test (`tests/graphql_http.rs`) parses this embedded SDL and
//! the on-disk `.gql` and asserts every type/field the Rust server implements is
//! byte-identical.
//!
//! ## `__typename` support
//!
//! Every GraphQL object type carries an implicit `__typename` meta-field
//! returning the object's type name as a `String`. The run-detail /
//! metric-history UI queries select `__typename` (see
//! `useSampledMetricHistoryGraphQL.tsx`), so the executor needs to know, for
//! each resolved object, what its GraphQL type name is. [`TYPE_NAMES`] records
//! that mapping keyed by a stable internal tag the resolvers attach to each
//! object they build.

/// The embedded GraphQL SDL, identical to
/// `mlflow/server/js/src/graphql/autogenerated_schema.gql`. Kept in lockstep by
/// the T6.2 schema-diff test.
pub const SCHEMA_SDL: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../../mlflow/server/js/src/graphql/autogenerated_schema.gql"
));

/// The GraphQL object-type name for each internal object tag the resolvers use.
/// The `__typename` meta-field resolves through this map. The tag strings are an
/// internal detail (not on the wire); the values are the exact GraphQL type
/// names from the SDL.
pub fn type_name(tag: &str) -> &'static str {
    match tag {
        "GetExperimentResponse" => "MlflowGetExperimentResponse",
        "GetRunResponse" => "MlflowGetRunResponse",
        "GetMetricHistoryBulkIntervalResponse" => "MlflowGetMetricHistoryBulkIntervalResponse",
        "ListArtifactsResponse" => "MlflowListArtifactsResponse",
        "SearchModelVersionsResponse" => "MlflowSearchModelVersionsResponse",
        "SearchRunsResponse" => "MlflowSearchRunsResponse",
        "SearchDatasetsResponse" => "MlflowSearchDatasetsResponse",
        "Experiment" => "MlflowExperiment",
        "ExperimentTag" => "MlflowExperimentTag",
        "Run" => "MlflowRunExtension",
        "RunInfo" => "MlflowRunInfo",
        "RunData" => "MlflowRunData",
        "RunInputs" => "MlflowRunInputs",
        "RunOutputs" => "MlflowRunOutputs",
        "Metric" => "MlflowMetricExtension",
        "MetricWithRunId" => "MlflowMetricWithRunId",
        "Param" => "MlflowParam",
        "RunTag" => "MlflowRunTag",
        "DatasetInput" => "MlflowDatasetInput",
        "Dataset" => "MlflowDataset",
        "InputTag" => "MlflowInputTag",
        "ModelInput" => "MlflowModelInput",
        "ModelOutput" => "MlflowModelOutput",
        "ModelVersion" => "MlflowModelVersion",
        "ModelVersionTag" => "MlflowModelVersionTag",
        "ModelParam" => "MlflowModelParam",
        "ModelMetric" => "MlflowModelMetric",
        "FileInfo" => "MlflowFileInfo",
        "DatasetSummary" => "MlflowDatasetSummary",
        "ApiError" => "ApiError",
        "ErrorDetail" => "ErrorDetail",
        "Test" => "Test",
        "TestMutation" => "TestMutation",
        // Should be unreachable for well-formed resolver output.
        _ => "Unknown",
    }
}

/// The root Query fields this server implements. Used by the schema-diff test to
/// scope the diff to implemented operations (everything else in the `.gql` is
/// allowlisted).
pub const IMPLEMENTED_QUERY_FIELDS: &[&str] = &[
    "mlflowGetExperiment",
    "mlflowGetMetricHistoryBulkInterval",
    "mlflowGetRun",
    "mlflowListArtifacts",
    "mlflowSearchModelVersions",
    "test",
    "mlflowSearchRuns",
];

/// The root Mutation fields this server implements.
pub const IMPLEMENTED_MUTATION_FIELDS: &[&str] =
    &["mlflowSearchDatasets", "mlflowSearchRuns", "testMutation"];
